- .travis.yml
I decided to play with Travis CI today. It's a continuous integration service that builds projects and returns pass/fail status. It has great Github support and will add badges to merge requests and commits letting you know if builds and tests worked properly.
It only took about 20 minutes to read the docs and get it working. You just need to sign into Travis with your Github account and turn on a tick box for this project. If it's okay here, I'll add it to the other projects in the avr-llvm umbrella.
It's fantastic
> Implement Travis-CI support

- .travis.yml
I haven't tested this, so we'll see with Travis if this will actually work correctly.
> Only build AVR target when going through Travis

- AVR_SUPPORT.md
This version is newer than the previously linked.
> Update AVR instruction set manual url

- .travis.yml
Fix build system. Can't use CMake 3 yet as there aren't prebuilt packages for 12.04. When Travis is on 14.04 and the build system breaks again, I'll upgrade it.
> Update CMake to 2.8.12.2

- .travis.yml
Since I was in the Travis build config anyway, decided to put it in place.
Tested with working CMake from other MR.
> Treat warnings as errors

- lib/Target/AVR/AsmParser/AVRAsmParser.cpp
- test/MC/AVR/inst-ldd.s
- test/MC/AVR/inst-std.s
_Ding_. Round two.
The instruction encoding for `ldd r2, Y+2` et al is still wonky. But parsing and matching works...
> Refactor asm parser even more

- lib/Target/AVR/AsmParser/AVRAsmParser.cpp
Goal is to implement the assembler directives listed in #24 that are unknown to llvm core:
> Implement assembler directives

- lib/Target/AVR/MCTargetDesc/AVRMCCodeEmitter.cpp
> Fixups: Expand modifiers to correct relocations

- lib/Target/AVR/AVRAsmPrinter.cpp
- lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp
- lib/Target/AVR/MCTargetDesc/AVRELFObjectWriter.cpp
- lib/Target/AVR/MCTargetDesc/AVRMCExpr.cpp
- lib/Target/AVR/MCTargetDesc/AVRMCExpr.h
- test/MC/AVR/oper-hilo8.s
Not so much a refactoring. It's more about finding the loose ends. I [enabled the relocation addend](https://github.com/avr-llvm/llvm/compare/avr-llvm:avr-support...agnat:feature/refactor_relocation_handling?expand=1#diff-a99a83bc01cc4a2046b1f1407492a553R41) and added code to handle [symbolic expressions](https://github.com/avr-llvm/llvm/compare/avr-llvm:avr-support...agnat:feature/refactor_relocation_handling?expand=1#diff-812a909bfbe7dd2e5ddb6120cec877d8R76).
````
foo: ldi r24, lo8(foo)
bar: ldi r24, hi8(bar)
````
````
$ llvm-mc -triple avr-none -filetype=obj foo.s -o foo_llvm.o
$ avr-as -mmcu=atmega32 foo.s -o foo_gas.o
````
````
$ avr-objdump -r foo_gas.o foo_llvm.o
foo_gas.o:     file format elf32-avr
RELOCATION RECORDS FOR [.text]:
OFFSET   TYPE              VALUE 
00000000 …
```
> Work on relocations

- lib/Target/AVR/AVRInstrInfo.td
- lib/Target/AVR/AVRRegisterInfo.td
- lib/Target/AVR/AsmParser/AVRAsmParser.cpp
Some instructions take an explicit Z register argument. By modeling this as a register class containing only the Z register we help the parser to cleanly match this syntax.
I think this also enables us to write isel patterns for these instructions. Not sure how important that is, though...
@dylanmckay review plz.
> AVRInstrInfo: Factor Z register into it's own register class

- lib/Target/AVR/AVRInstrInfo.td
- test/CodeGen/AVR/call.ll
Adjust register names and regular expressions in call.ll to match our (current) register name pretty printing. This is a fix by result.
@dylanmckay, could you take a second to review this?
> Fixed call.ll code gen test

- lib/Target/AVR/AVRExpandPseudoInsts.cpp
- lib/Target/AVR/AVRISelDAGToDAG.cpp
- lib/Target/AVR/AVRISelLowering.cpp
- lib/Target/AVR/AVRISelLowering.h
- lib/Target/AVR/AVRInstrInfo.td
- test/CodeGen/AVR/mul.ll
Sorry for being longish, but I think it is important to share my thoughts...
So... As mentioned in #126 I believe pseudo instructions are not the way to go. Instead of guiding the initial lowering towards instructions we actually support we encourage the emission of instructions we don't have. Down the pipeline we have trouble expanding these pseudos, because we suddenly have to do this weird manual register lifetime management, which is error prone and... overall pretty disgusting.
I also believe it is bad for optimization. We do not describe the _actual_ instruction set. We create a new _virtual_ instruction set, which hides the details.
Let's try something else. Looking at the AVR `mul` instructions they are a lot closer to the …
> Better Multiplication

- lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp
- lib/Target/AVR/MCTargetDesc/AVRAsmBackend.h
- lib/Target/AVR/MCTargetDesc/AVRFixupKinds.h
- lib/Target/AVR/MCTargetDesc/AVRMCCodeEmitter.cpp
Pass fixup value by reference to adjustFooBar(...) functions, adjusting the value in-place. Drop a missleading comment in processFixupValue(...).
I think it's a little less confusing this way... @dylanmckay, could you give it a review and maybe re-run your test case?
> [AVR] Touch up fixups

- lib/Target/AVR/AsmParser/AVRAsmParser.cpp
- lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp
- test/MC/AVR/inst-brbc.s
- test/MC/AVR/inst-brbs.s
- test/MC/AVR/inst-family-cond-branch.s
- test/MC/AVR/inst-rcall.s
- test/MC/AVR/inst-rjmp.s
Beforehand, if a PC-relative branch target was parsed (in `AVRAsmParser.cpp`), we threw away the `.` token and then delegated the operand parsing to LLVM.
Now, if we see the `.` token, we give it to LLVM so that it can handle the address itself. LLVM will create a temporary label for each PC-relative branch, and use that.
> Fix branch handling code

- lib/Target/AVR/AVRISelLowering.cpp
- test/CodeGen/AVR/lower-formal-arguments-assertion.ll
Integer division was rounding off `i1` to take 0 bytes.
Closes #173
> 1-bit types consume one byte of space, not zero

- lib/Target/AVR/AVRAsmPrinter.cpp
AVRAsmPrinter was crashing randomly for me, this fixed it.
> [AVR] Fix uninitialized MRI in AVRAsmPrinter

- test/CodeGen/AVR/load.ll
- test/CodeGen/AVR/store.ll
Partially fixes #27 by updating load/store tests to match with currently generated output.
> [AVR] fix load/store tests

- .travis.yml
- lib/Target/AVR/AVRExpandPseudoInsts.cpp
- lib/Target/AVR/AVRFrameLowering.cpp
- lib/Target/AVR/AVRFrameLowering.h
- lib/Target/AVR/AVRISelDAGToDAG.cpp
- lib/Target/AVR/AVRISelLowering.cpp
- lib/Target/AVR/AVRTargetMachine.cpp
- test/CodeGen/AVR/calling-conv-assertion.ll
- test/CodeGen/AVR/impossible-reg-to-reg-copy.ll
- test/CodeGen/AVR/issue-cannot-select-mulhs.ll
We should probably look closer at 9ed38db20eac20ba78c7daf6970324612cd0d60f to see if we can follow those changes closely.
> Compile again, after tracking upstream changes

- lib/Target/AVR/AVRInstrInfo.td
- lib/Target/AVR/InstPrinter/AVRInstPrinter.cpp
- lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp
- lib/Target/AVR/MCTargetDesc/AVRMCCodeEmitter.cpp
- lib/Target/AVR/MCTargetDesc/AVRMCCodeEmitter.h
- test/MC/AVR/inst-adiw.s
- test/MC/AVR/inst-andi.s
- test/MC/AVR/inst-cbi.s
- test/MC/AVR/inst-cpi.s
- test/MC/AVR/inst-in.s
- test/MC/AVR/inst-jmp.s
- test/MC/AVR/inst-ldd.s
- test/MC/AVR/inst-ldi.s
- test/MC/AVR/inst-ori.s
- test/MC/AVR/inst-out.s
- test/MC/AVR/inst-sbci.s
- test/MC/AVR/inst-sbi.s
- test/MC/AVR/inst-sbic.s
- test/MC/AVR/inst-sbis.s
- test/MC/AVR/inst-sbiw.s
- test/MC/AVR/inst-sbr.s
- test/MC/AVR/inst-std.s
- test/MC/AVR/inst-subi.s
It was discovered in #184 that _some_ instructions would silently ignore relocatable expressions (i.e. `SYMBOL` or `SYMBOL+4`) in place of immediates, and set them to zero.
This PR adds support for expressions to other instructions which are missing it.
> Allow relocatable expressions in more places

- lib/CodeGen/RegAllocGreedy.cpp
- lib/Target/AVR/AVRInstrInfo.cpp
This is unnecessary, and required that we added an AVR-specific hack to
the register allocator.
Fixes #145
> [AVR] Don't reserve the frame pointer when spilling registers

- lib/CodeGen/CalcSpillWeights.cpp
- lib/CodeGen/RegAllocGreedy.cpp
- test/CodeGen/AVR/high-pressure-on-ptrregs.ll
Previously, when allocating unspillable live ranges, we would never
attempt to split. We would always bail out and try last ditch graph
recoloring.
This patch changes this by attempting to split all live intervals before
performing recoloring.
This fixes issue #1
> WIP: [RegAllocGreedy] Attempt to split unspillable live intervals
